apiVersion: 1

datasources:
  - name: netstats
    type: influxdb
    access: server
    database: netstats
    user: $INFLUXDB_USERNAME
    password: $INFLUXDB_PASSWORD
    url: $INFLUXDB_URL
    jsonData:
      httpMode: GET

  - name: starlinkstats
    type: influxdb
    access: server
    database: starlinkstats
    user: $INFLUXDB_USERNAME
    password: $INFLUXDB_PASSWORD
    url: $INFLUXDB_URL
    jsonData:
      httpMode: GET
